### ISSUE TITLE
Unable to compile into Xcode 9

### ISSUE THREAD

**Issue by julien-fieschi** [AFSR/RettApp#2]
Migration to swift 4 make it unable to compile and build into Xcode 9.

**Comment by BENMESSAOUD** [comment]
Bonjour, 
Je vais regarder comment le faire compiler. 
je vous tiens au courant.

**Comment by BENMESSAOUD** [comment]
Okay j'ai un build succeeded 👍 :)
![simulator screen shot - iphone 5 - 2018-01-19 at 10 22 08](https://user-images.githubusercontent.com/409757/35143840-0168e6a2-fd03-11e7-90d4-ca7b8f75ecfa.png)
![simulator screen shot - iphone 5 - 2018-01-19 at 10 25 40](https://user-images.githubusercontent.com/409757/35143911-35f7750a-fd03-11e7-9490-333045d7a917.png)
![simulator screen shot - iphone 5 - 2018-01-19 at 10 26 20](https://user-images.githubusercontent.com/409757/35143912-36114264-fd03-11e7-949b-adaf041c5d38.png)
